services:
  keycloak:
    container_name: keycloak
    build:
      context: keycloak
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
      - "8443:8443"
    depends_on:
      - keycloak-postgres
    environment:
      KC_HEALTH_ENABLED: 'true'
      KC_METRICS_ENABLED: 'true'
      KC_DB: postgres
      KC_DB_URL: "jdbc:postgresql://keycloak-postgres/keycloak"
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: keycloak
      KC_HOSTNAME: localhost
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_PROXY_HEADERS: xforwarded
      PROXY_ADDRESS_FORWARDING: "true"
    command:
      - "-v"
      - "start"
      - "--optimized"
      - "--spi-x509cert-lookup-nginx-ssl-client-cert=SSL_CLIENT_CERT"
      - "--spi-x509cert-lookup-nginx-ssl-cert-chain-prefix=CERT_CHAIN"
      - "--spi-x509cert-lookup-nginx-certificate-chain-length=10"

  keycloak-postgres:
    container_name: keycloak-postgres
    image: postgres:16
    restart: unless-stopped
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: keycloak
      PGDATA: /var/lib/postgresql/data/db-files/
    volumes:
      - postgres-data:/var/lib/postgresql/data/db-files

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    container_name: nginx
    ports:
      - "80:80"
    depends_on:
      - keycloak

volumes:
  postgres-data: {}
